import enum


class PlatformEnum(str, enum.Enum):
    """Enum for the platform of the ticket."""

    JIRA = "JIRA"
    GITHUB = "GITHUB"
    TRELLO = "TRELLO"
    ASANA = "ASANA"  # Add more platforms as needed


class EventEnum(str, enum.Enum):
    """Enum representing the type of event."""

    TICKET_GENERATION = "TICKET_GENERATION"
    TICKET_EXPANSION = "TICKET_EXPANSION"
    TICKET_UPDATE = "TICKET_UPDATE"
    TICKET_DELETION = "TICKET_DELETION"
    TICKET_RETRIEVAL = "TICKET_RETRIEVAL"
    TICKET_CREATION = "TICKET_CREATION"
    TICKET_ASSIGNMENT = "TICKET_ASSIGNMENT"
    TICKET_COMMENT = "TICKET_COMMENT"
    TICKET_STATUS_CHANGE = "TICKET_STATUS_CHANGE"
    TICKET_PRIORITY_CHANGE = "TICKET_PRIORITY_CHANGE"
    TICKET_RESOLUTION_CHANGE = "TICKET_RESOLUTION_CHANGE"
    TICKET_TYPE_CHANGE = "TICKET_TYPE_CHANGE"
    TICKET_LABEL_CHANGE = "TICKET_LABEL_CHANGE"
    TICKET_EPIC_CHANGE = "TICKET_EPIC_CHANGE"
    TICKET_SPRINT_CHANGE = "TICKET_SPRINT_CHANGE"
    TICKET_COMPONENT_CHANGE = "TICKET_COMPONENT_CHANGE"
    TICKET_FIX_VERSION_CHANGE = "TICKET_FIX_VERSION_CHANGE"
    TICKET_AFFECTS_VERSION_CHANGE = "TICKET_AFFECTS_VERSION_CHANGE"
    TICKET_DUE_DATE_CHANGE = "TICKET_DUE_DATE_CHANGE"
    TICKET_ESTIMATION_POINTS_CHANGE = "TICKET_ESTIMATION_POINTS_CHANGE"
    TICKET_REPORTER_CHANGE = "TICKET_REPORTER_CHANGE"
    TICKET_ASSIGNEE_CHANGE = "TICKET_ASSIGNEE_CHANGE"
    TICKET_WATCHER_CHANGE = "TICKET_WATCHER_CHANGE"
    TICKET_LINK = "TICKET_LINK"
    TICKET_ATTACHMENT = "TICKET_ATTACHMENT"
    TICKET_SUBTASK = "TICKET_SUBTASK"
    TICKET_EPIC = "TICKET_EPIC"
    TICKET_SPRINT = "TICKET_SPRINT"
    TICKET_COMPONENT = "TICKET_COMPONENT"
    TICKET_FIX_VERSION = "TICKET_FIX_VERSION"
    TICKET_AFFECTS_VERSION = "TICKET_AFFECTS_VERSION"
    TICKET_DUE_DATE = "TICKET_DUE_DATE"
    TICKET_ESTIMATION_POINTS = "TICKET_ESTIMATION_POINTS"
    TICKET_REPORTER = "TICKET_REPORTER"
    TICKET_ASSIGNEE = "TICKET_ASSIGNEE"
    TICKET_WATCHER = "TICKET_WATCHER"
